"use client";

import { Loader2 } from "lucide-react";
import type { ProjectDraft } from "@/types/verify-project";

interface Form7AgreementProps {
  draft: ProjectDraft;
  errors: Record<string, string>;
  isSubmitting: boolean;
  onFieldChange: <K extends keyof ProjectDraft>(
    key: K,
    value: ProjectDraft[K],
  ) => void;
  onSubmit: () => void;
}

export default function Form7Agreement({
  draft,
  errors,
  isSubmitting,
  onFieldChange,
  onSubmit,
}: Form7AgreementProps) {
  const allChecked =
    draft.agreement_voluntary &&
    draft.agreement_right_to_sell &&
    draft.agreement_not_sold_elsewhere &&
    draft.agreement_marketplace;

  return (
    <section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-black/5">
      <h3 className="text-xl font-semibold text-gray-900">Final Agreement</h3>
      <p className="mt-1 text-sm text-gray-500">
        Please read and agree to all terms before submitting your project for
        review.
      </p>

      <div className="mt-5 space-y-4">
        <label className="flex items-start gap-2 text-sm text-gray-700">
          <input
            type="checkbox"
            checked={draft.agreement_voluntary}
            disabled={isSubmitting}
            onChange={(event) =>
              onFieldChange("agreement_voluntary", event.target.checked)
            }
            className="mt-1 h-4 w-4 accent-green-600"
          />
          <span>
            This project is a voluntary carbon offset initiative and is not
            required by any regulatory mandate.
          </span>
        </label>
        {errors.agreement_voluntary ? (
          <p className="text-xs text-red-500">{errors.agreement_voluntary}</p>
        ) : null}

        <label className="flex items-start gap-2 text-sm text-gray-700">
          <input
            type="checkbox"
            checked={draft.agreement_right_to_sell}
            disabled={isSubmitting}
            onChange={(event) =>
              onFieldChange("agreement_right_to_sell", event.target.checked)
            }
            className="mt-1 h-4 w-4 accent-green-600"
          />
          <span>
            ZeroCarbon marketplace has the right to list and facilitate the sale
            of carbon credits generated by this project on its platform.
          </span>
        </label>
        {errors.agreement_right_to_sell ? (
          <p className="text-xs text-red-500">
            {errors.agreement_right_to_sell}
          </p>
        ) : null}

        <label className="flex items-start gap-2 text-sm text-gray-700">
          <input
            type="checkbox"
            checked={draft.agreement_not_sold_elsewhere}
            disabled={isSubmitting}
            onChange={(event) =>
              onFieldChange("agreement_not_sold_elsewhere", event.target.checked)
            }
            className="mt-1 h-4 w-4 accent-green-600"
          />
          <span>
            The carbon credits from this project have not been sold or listed on
            any other platform. I understand that if found otherwise, penalties
            will apply.
          </span>
        </label>
        {errors.agreement_not_sold_elsewhere ? (
          <p className="text-xs text-red-500">
            {errors.agreement_not_sold_elsewhere}
          </p>
        ) : null}

        <label className="flex items-start gap-2 text-sm text-gray-700">
          <input
            type="checkbox"
            checked={draft.agreement_marketplace}
            disabled={isSubmitting}
            onChange={(event) =>
              onFieldChange("agreement_marketplace", event.target.checked)
            }
            className="mt-1 h-4 w-4 accent-green-600"
          />
          <span>
            I agree to the ZeroCarbon Marketplace Terms of Service, Carbon Credit
            Listing Policy, and Seller Code of Conduct.
          </span>
        </label>
        {errors.agreement_marketplace ? (
          <p className="text-xs text-red-500">{errors.agreement_marketplace}</p>
        ) : null}
      </div>

      <button
        type="button"
        onClick={onSubmit}
        disabled={!allChecked || isSubmitting}
        className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-green-600 px-4 py-3 text-sm font-semibold text-white transition-colors hover:bg-green-700 disabled:cursor-not-allowed disabled:opacity-60"
      >
        {isSubmitting ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
        Submit Application
      </button>
    </section>
  );
}
